environment:
    matrix:
    # node.js
    - nodejs_version: "8"
    - nodejs_version: "9"

platform:
    - x86
    - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - npm run test

build: off 